# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=10)),
                ('s_tel', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'day51_student',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_addr', models.CharField(max_length=30)),
                ('s', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stu.Student')),
            ],
            options={
                'db_table': 'day51_Student_info',
            },
        ),
    ]
