# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_dex',
            new_name='stu_sex',
        ),
    ]
