# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ticket',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
